name: Windows Commands Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-windows-commands:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: create vps
        shell: cmd
        run: |
          net user banana /add
          net user banana Parsa@123
          dism /Online /Add-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0
          net start sshd
          sc config sshd start=auto
          netsh advfirewall firewall add rule name="OpenSSH Server" dir=in action=allow protocol=TCP localport=22
          ipconfig
          echo successfully, user: banana, pass: Parsa@123 .
